# Dependencies
markdown:         redcarpet
pygments:         true

# Analytics
analytics :
  tracking_id :   'UA-6856454-4'
  site_name:      'sergiou87.github.io'

# Permalinks
permalink:        pretty

# Setup
excerpt_separator: <!--more-->

title:            'Sergio Padrino'
tagline:          'A blog about iOS development'
description:      "In this blog I'll write about my work and thoughts as iOS developer."
url:              http://sergiou87.github.io

author:
  name:           'Sergio Padrino'
  url:            https://twitter.com/sergiou87

paginate:         5

# Custom vars
github:           https://github.com/sergiou87
twitter:          https://twitter.com/sergiou87
linkedin:         https://www.linkedin.com/profile/view?id=161276523
